SELECT `ScreePrintSAMs`.`sam_id`,
    `ScreePrintSAMs`.`COD_SAM`,
    `ScreePrintSAMs`.`Cod_Sam_Vuelta`,
    `ScreePrintSAMs`.`Localidad`,
    `ScreePrintSAMs`.`Maquina`,
    `ScreePrintSAMs`.`Pantallas`,
    `ScreePrintSAMs`.`TiempoSetup`,
    `ScreePrintSAMs`.`Vuelta`,
    `ScreePrintSAMs`.`TipoRecorrido`,
    `ScreePrintSAMs`.`TCarga`,
    `ScreePrintSAMs`.`TImp1`,
    `ScreePrintSAMs`.`TImp2`,
    `ScreePrintSAMs`.`TImp3`,
    `ScreePrintSAMs`.`TImp4`,
    `ScreePrintSAMs`.`TImp5`,
    `ScreePrintSAMs`.`TImp6`,
    `ScreePrintSAMs`.`TImp7`,
    `ScreePrintSAMs`.`TImp8`,
    `ScreePrintSAMs`.`TImp9`,
    `ScreePrintSAMs`.`Descarga`,
    `ScreePrintSAMs`.`Inspeccion`,
    `ScreePrintSAMs`.`Tag`,
    `ScreePrintSAMs`.`Aux`,
    `ScreePrintSAMs`.`Impr`,
    `ScreePrintSAMs`.`ImprAuto`,
    `ScreePrintSAMs`.`Insp`,
    `ScreePrintSAMs`.`TiempoCicloSeg`,
    `ScreePrintSAMs`.`TiempoCicloMin`,
    `ScreePrintSAMs`.`ID`
FROM `wordpress`.`ScreePrintSAMs`;


